version: ImageMagick-{branch}.{build}

os: Visual Studio 2013

clone_folder: C:\ImageMagick
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: false

cache:
  - C:\Strawberry-x86 -> AppVeyor\Install.cmd
  - C:\Strawberry-x64 -> AppVeyor\Install.cmd

environment:

  matrix:
    - im_platform: "x86"
      im_name:     "deps-dll-Q16"
      im_vstudio:  "VS2015"
      im_toolset:  "v140"

install:
  - cd AppVeyor
  - Install.cmd %im_platform%

artifacts:
  - path: 'Windows-Distribution\*.exe'
  - path: 'Windows-Distribution\*.zip'

build_script:
  - cd AppVeyor
  - Build.cmd %im_platform% %im_name% %im_vstudio% %im_toolset%

test: off
