version: ImageMagick-{branch}.{build}

os: Visual Studio 2017

clone_folder: C:\ImageMagick
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:
  - C:\InnoSetup -> AppVeyor\Install.cmd

environment:

  matrix:
    - im_platform:  "x86"
      im_name:      "deps-dll-Q16"
      im_vstudio:   "VS2017"
      im_vcversion: "vc15"
      im_toolset:   "v141"

    - im_platform:  "x64"
      im_name:      "deps-dll-Q16"
      im_vstudio:   "VS2017"
      im_vcversion: "vc15"
      im_toolset:   "v141"

    - im_platform:  "x86"
      im_name:      "deps-dll-Q16"
      im_vstudio:   "VS2015"
      im_vcversion: "vc14"
      im_toolset:   "v140"

    - im_platform:  "x64"
      im_name:      "deps-dll-Q16"
      im_vstudio:   "VS2015"
      im_vcversion: "vc14"
      im_toolset:   "v140"

    - im_platform:  "none"
      im_name:      "source"

install:
  - cd AppVeyor
  - Install.cmd %im_platform%

artifacts:
  - path: 'Windows-Distribution\*.exe'
  - path: 'Windows-Distribution\*.zip'

build_script:
  - cd AppVeyor
  - dir C:\ImageMagick\LICENSE /s
  - Build.cmd %im_platform% %im_name% %im_vstudio% %im_vcversion% %im_toolset%
  
test: off
