version: ImageMagick-{branch}.{build}

clone_folder: C:\ImageMagick
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

environment:

  matrix:
    - im_platform: "x64"
      im_name:     "dll-Q16"
      vstudio:     "VS2015"
      toolset:     "v140"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
    - im_platform: "x86"
      im_name:     "dll-Q16"
      vstudio:     "VS2015"
      toolset:     "v140"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"

install:
  - cd AppVeyor
  - Install.cmd %im_platform% %im_name% %vstudio% %toolset%

artifacts:
  - path: 'Windows-Distribution\*.exe'
  - path: 'Windows-Distribution\*.zip'
  - path: 'Windows-Distribution\Version.txt'

build_script:
  - cd AppVeyor
  - Build.cmd %im_platform% %im_name% %vstudio% %toolset%

test: off

branches:
    only:
        - ImageMagick-Windows-7
